services:
  ecoute-client:
    image: nginx:latest
    container_name: ecoute-client
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
      - ./web/error.html:/usr/share/nginx/html/error.html
      - ./web/sorry.html:/usr/share/nginx/html/sorry.html
    ports:
      - 8080:80